# OBJ= main.o helpers.o setup_graphics.o 

# # Fix the directories to match your file organisation.
# CC_FLAGS=-std=gnu99 -I../../ZDK -Wall -Werror -g
# LD_FLAGS=-L../../ZDK -lzdk -lncurses -lm

# a1_n5377544: $(OBJ)
# 	gcc $(OBJ) $(LD_FLAGS) -o $@

# %.o : %.c
# 	gcc -c $< $(CC_FLAGS)


# # Makefile for the CAB202_n10026924

# OBJ = CAB202_n10026924.c helpers.c

# FLAGS = -std=gnu99 -I../ZDK -Wall -Werror -g -L../ZDK -lzdk -lncurses -lm

# A1_n10026924: $(OBJ)
# 	gcc $(OBJ) $(FLAGS) -o $@

#Makefile for a1_n5377544

OBJ = main.c helpers.c setup_graphics.c
FLAGS = -std=gnu99 -I../ZDK -Wall -Werror -g -L../ZDK -lzdk -lncurses -lm
a1_n5377544: $(OBJ)
	gcc $(OBJ) $(FLAGS) -o $@
